### ISSUE TITLE
"Refresh to enjoy new features." popping up repeatedly

### ISSUE THREAD

**Issue by MelBourbon** [hackmdio/codimd#1213]
I deployed by docker and restored my existing database. Now I get the new feature message as shown below every time I open a note and it pops up again every time I reload. Deleting browser cache did not resolved this. 

![image](https://user-images.githubusercontent.com/30600002/57407430-740c7880-71e3-11e9-8931-1753adad89ef.png)

Any ideas why this is now occurring again? Because this was resolved with #847

**Comment by a60814billy** [comment]
please switch on `debug` mode and provide more log to let us debugging, thanks!

**Comment by Yukaii** [comment]
This problem might be related these code:

https://github.com/hackmdio/codimd/blob/573501389a5644c0feacb4eca7155b9e3322f047/public/js/index.js#L1774-L1783

@MelBourbon Could you open Chrome DevTools and access `window.version` variable and see what it is? Thx

**Comment by MelBourbon** [comment]
@Yukaii `window.version` seems to be `undefined` and `<not available>` during reload. Is this helpful.

![image](https://user-images.githubusercontent.com/30600002/57448693-4d3d5900-725a-11e9-91d0-65600e859de5.png)

![image](https://user-images.githubusercontent.com/30600002/57448717-59c1b180-725a-11e9-83ec-b22bcd80dac5.png)

**Comment by Yukaii** [comment]
@MelBourbon Are there any red lines (error log) in the DevTool console?

Also please provide the version of your docker image. 😄

**Comment by MelBourbon** [comment]
@Yukaii Yes, there are (see below). The version of the docker image is 1.2.0

![image](https://user-images.githubusercontent.com/30600002/57457171-4e2cb580-726f-11e9-9a18-2fdc5214ba21.png)

**Comment by Yukaii** [comment]
Our latest image version is 1.3.1 and this issue should be fixed in that version. Please upgrade to that version 😸

**Comment by MelBourbon** [comment]
@Yukaii You are right, this fixed it. But please note, your CodiMD documentation for Docker Deployment references to your archived container repository https://github.com/hackmdio/docker-hackmd. In this repository the `docker-compose.yml` uses 1.2.0 of the docker. So I recommend to update this because this is misleading. I will keep this open if you consider this. Feel free to close the issue if you don't see the need.

https://github.com/hackmdio/docker-hackmd/blob/55c58abb016ec93d80add8c2b08c90876cac48ed/docker-compose.yml#L48-L56

**Comment by Yukaii** [comment]
We'll update it, thanks for reminding us :)

**Comment by MelBourbon** [comment]
`image: hackmdio/hackmd:1.2.0` is still existing in docker-compose.yml
